configuration: Release

version: 1.0.{build}
environment:
  name: flyte
build:
  project: flyte.sln
  verbosity: minimal
deploy:
- provider: GitHub
  tag: EXPERIMENTAL
  release: Experimental Release
  description: 'This is an experimental release build from the latest commit. Try at your own risk!\n\nMessage: $(APPVEYOR_REPO_COMMIT_MESSAGE)\n\n Timestamp: $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  auth_token:
    secure: UzGKRf2KUa75tPxtxdqR4Kjvcz9AijUxgki9/On08gcFWqA6tXtl7MP0WDC84oWO
  repository: flyte
  artifact: flyte-Latest.zip
  draft: false
  prerelease: true
  force_update: true
 
after_build:
  - 7z a "flyte-Latest.zip" "%APPVEYOR_BUILD_FOLDER%\flyte\bin\Release\flyte.exe"
  - 7z a "flyte-Latest.zip" "%APPVEYOR_BUILD_FOLDER%\flyte\bin\Release\flyte.exe.config"
  - 7z a "flyte-Latest.zip" "%APPVEYOR_BUILD_FOLDER%\flyte\bin\Release\flyte.pdb"
  - appveyor PushArtifact "flyte-Latest.zip"